name: Build Windows IPv6 fix

on:
  push:
    branches:
      - 'build/windows-ipv6-fix'
  workflow_dispatch:

env:
  QT_MIRROR: https://mirrors.ocf.berkeley.edu/qt/

jobs:
  build-windows:
    runs-on: windows-latest

    env:
      QT_VERSION: 6.10.1
      QIF_VERSION: 4.7
      PROD_AGW_PUBLIC_KEY: ${{ secrets.PROD_AGW_PUBLIC_KEY }}
      PROD_S3_ENDPOINT: ${{ secrets.PROD_S3_ENDPOINT }}
      FALLBACK_S3_ENDPOINT: ${{ secrets.FALLBACK_S3_ENDPOINT }}
      DEV_AGW_PUBLIC_KEY: ${{ secrets.DEV_AGW_PUBLIC_KEY }}
      DEV_AGW_ENDPOINT: ${{ secrets.DEV_AGW_ENDPOINT }}
      DEV_S3_ENDPOINT: ${{ secrets.DEV_S3_ENDPOINT }}
      FREE_V2_ENDPOINT: ${{ secrets.FREE_V2_ENDPOINT }}
      PREM_V1_ENDPOINT: ${{ secrets.PREM_V1_ENDPOINT }}

    steps:
      - name: Get sources
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 10

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2022_64'
          modules: 'qtremoteobjects qt5compat qtshadertools'
          dir: ${{ runner.temp }}
          setup-python: 'true'
          tools: 'tools_ifw'
          set-env: 'true'
          aqtversion: '==3.3.0'
          py7zrversion: '==0.22.*'
          extra: '--base ${{ env.QT_MIRROR }}'

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: 'x64'

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install WiX Toolset
        shell: powershell
        run: |
          dotnet tool install --global wix --version 4.0.6
          wix extension add -g WixToolset.UI.wixext/4.0.6
          wix extension add -g WixToolset.Util.wixext/4.0.6
          wix extension list -g
          $wixBinDir = Join-Path $env:USERPROFILE ".dotnet\tools"
          echo "WIX_BIN_DIR=$wixBinDir" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.14

      - name: Install Conan
        run: pip install "conan==2.28.0"

      - name: Build project
        shell: cmd
        env:
          QT_INSTALL_DIR: ${{ runner.temp }}
        run: |
          set WIX_ROOT_PATH="${{ env.USERPROFILE }}\.dotnet\tools"
          deploy\build.bat --installer all

      - name: Upload Windows EXE
        uses: actions/upload-artifact@v4
        with:
          name: AmneziaVPN-Windows-IPv6-fix
          path: deploy/build/AmneziaVPN_*_windows_x64.exe
          if-no-files-found: error
          retention-days: 7
